resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps/code-pipeline-templates
      ref: 'develop'

pool:
  vmImage: ubuntu-latest

stages:
- stage: CodeCheck
  displayName: Code Check

  jobs:

    - template: NetCore/codecheck/dnc-codecheck-v2.yml@templates
      parameters: 
        ChangeDotNetVersion: true
        CreateSonarProject: true
        ConfigSonarProject: true
        RunCoverageTests: true
        CoverageTestsResults: true
        RunSonarAnalysis: true
        PublishSonarResults: true
        PublishCoverageResults: true
        PublishTestsResults: true
        ValidateSonarQualityGate: true
         
        DotnetVersion: 6.0.x
        DotnetSonarVersion: 6.0.x
        producto: plantilla
        equipo: ingenieria

        sonarCoverageExclude: ''